---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  roles_path: roles
  playbook: playbooks/st2express.yaml
  ansible_verbose: true
  ansible_verbosity: 3

platforms:
   - name: ubuntu-12.04
     driver:
       box: fgrehm/precise64-lxc
       provider: lxc
       boot_timeout: 600

suites:
  - name: default
    run_list:
    attributes:

verifier:
  ruby_bindir: '/usr/bin'
