---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  roles_path: roles
  playbook: playbooks/st2express.yaml
  ansible_verbose: true
  ansible_verbosity: 2

platforms:
  - name: ubuntu-12.04
    driver:
      box: precise-lxc
      provider: lxc

suites:
  - name: default
    run_list:
    attributes:

verifier:
  ruby_bindir: '/usr/bin'
