---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  roles_path: roles
  playbook: playbooks/st2express.yaml
  ansible_verbose: true
  ansible_verbosity: 2

platforms:
  - name: ubuntu-14.04
    driver_config:
      privileged: true
      disable_upstart: false
      image: phusion/baseimage
      platform: ubuntu

suites:
  - name: default
    run_list:
    attributes:

verifier:
  ruby_bindir: '/usr/bin'
