sudo: required
language: ruby
rvm:
  - "1.9.3"
install:
  - sudo apt-get update
  - gem install bundler -v 1.10.6 --no-rdoc --no-ri
  - bundle
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - sudo vagrant plugin install vagrant-lxc

script:
  - bundle exec kitchen test ubuntu-14
