sudo: required
language: ruby

services:
  - docker

install:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-cache search linux-headers-virtual
  - sudo apt-get -y install linux-headers-virtual
  - sudo apt-get -y install virtualbox-4.2
  - VBoxManage -v
  - gem install bundler --version 1.10.5 --no-rdoc --no-ri
  - bundle
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - vagrant plugin install vagrant-lxc

script:
  - export VAGRANT_LOG=info
  - bundle exec kitchen test ubuntu-12
